name: Build Kernel

on:
  workflow_dispatch:
    inputs:
      BRANCH_GIT_URL:
        description: 'BRANCH_GIT_URL to clone kernel source'
        required: true
        default: '-b A225FXXSADXK2 https://github.com/SN-Abdullah-Al-Noman/SM-A225X'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1️⃣ Checkout code
        uses: actions/checkout@v2

      - name: 2️⃣ Installing packages.
        run: |
          sudo apt update -y && sudo apt upgrade -y && sudo apt install nano bc bison ca-certificates curl flex gcc git libc6-dev libssl-dev openssl python-is-python3 ssh wget zip zstd sudo make clang gcc-arm-linux-gnueabi software-properties-common build-essential libarchive-tools gcc-aarch64-linux-gnu -y && sudo apt install build-essential -y && sudo apt install libssl-dev libffi-dev libncurses5 libncurses5-dev zlib1g zlib1g-dev libreadline-dev libbz2-dev libsqlite3-dev make gcc -y && sudo apt install pigz -y && sudo apt install python2 -y && sudo apt install python3 -y && sudo apt install cpio -y && sudo apt install lld -y && sudo apt install p7zip-full -y && sudo apt install python3-pip && pip3 install pyrogram && pip3 install tgcrypto

      - name: 3️⃣ Cloning kernel source.
        run: |
          git clone ${{ github.event.inputs.BRANCH_GIT_URL }} kernel_source

      - name: 4️⃣ Cloning toolchain.
        run: |
          cd kernel_source && sudo git clone https://github.com/SN-Abdullah-Al-Noman/toolchain
          
      - name: 5️⃣ Starting kernel compile.
        run: |
          cd kernel_source && bash build_kernel.sh

      - name: 6️⃣ Uploading kernel in telegram.
        run: |
          sudo 7z a -mx9 kernel_source/arch/arm64/boot/Image.xz kernel_source/arch/arm64/boot/Image && sudo curl -F chat_id=2081111916 -F document=@kernel_source/arch/arm64/boot/Image.xz -F caption="Image.xz" https://api.telegram.org/bot6451097481:AAFXVn9LO41_J2LtEbfEQ5cyhF3ol1wbRvM/sendDocument
