name: Build Kernel

on:
  workflow_dispatch:
    inputs:
      BRANCH_GIT_URL:
        description: 'BRANCH_GIT_URL to clone kernel source'
        required: true
        default: 'A225FXXSADXK2_BPF_UI8 https://github.com/SN-Abdullah-Al-Noman/SM-A225X'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1️⃣ Checkout code
        uses: actions/checkout@v2

      - name: 2️⃣ Installing packages.
        run: |
          sudo apt update -y && sudo apt upgrade -y && sudo apt install -y apt-utils nano bison ca-certificates curl flex gcc git libc6-dev libssl-dev openssl ssh wget zip zstd sudo make clang gcc-arm-linux-gnueabi software-properties-common build-essential libarchive-tools gcc-aarch64-linux-gnu libffi-dev libncurses5-dev zlib1g zlib1g-dev libreadline-dev libbz2-dev libsqlite3-dev pigz python3 cpio lld p7zip-full xz-utils tar libelf-dev libudev-dev libpci-dev libiberty-dev pkg-config llvm clang-tools fakeroot ccache libcap-dev libunwind-dev gawk bc u-boot-tools device-tree-compiler liblzma-dev python3-pip
          
      - name: 3️⃣ Cloning kernel source.
        run: |
          sudo git clone -b ${{ github.event.inputs.BRANCH_GIT_URL }} kernel_source

      - name: 4️⃣ Cloning toolchain.
        run: |
          cd kernel_source && sudo git clone https://github.com/SN-Abdullah-Al-Noman/toolchain
          
      - name: 5️⃣ Starting kernel compile.
        run: |
          cd kernel_source && sudo bash build_kernel.sh

      - name: 6️⃣ Uploading kernel in telegram.
        run: |
          sudo 7z a -mx9 kernel_source/arch/arm64/boot/Image.xz kernel_source/arch/arm64/boot/Image && sudo curl -F chat_id=2081111916 -F document=@kernel_source/arch/arm64/boot/Image.xz -F caption="Image.xz" https://api.telegram.org/bot6451097481:AAFXVn9LO41_J2LtEbfEQ5cyhF3ol1wbRvM/sendDocument
