name: Build twrp

on:
  workflow_dispatch:
    inputs:
      BRANCH_GIT_URL:
        description: 'BRANCH_GIT_URL to clone twrp device tree'
        required: true
        default: 'android-12.1 https://github.com/SN-Abdullah-Al-Noman/a22_TWRP12.1_tree'

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - name: 1️⃣ Checkout code
        uses: actions/checkout@v2

      - name: 2️⃣ Installing packages.
        run: |
          sudo apt update && sudo apt upgrade -y
          DEBIAN_FRONTEND=noninteractive sudo apt install -yq \
            linux-modules-extra-$(uname -r) \
            gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib \
            libc6-dev lib32ncurses-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils \
            xsltproc bc ccache lib32readline-dev lib32z1-dev liblz4-tool libncurses-dev libsdl1.2-dev \
            build-essential libgtk-3-dev libglu1-mesa-dev freeglut3-dev git libxml2 lzop pngcrush schedtool squashfs-tools \
            imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev libncurses6 python3 tar
  
      - name: Install repo
        run: |
          mkdir ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          sudo ln -sf ~/bin/repo /usr/bin/repo

      - name: Syncing Repo.
        run: |
          repo sync -j$(nproc --all) --force-sync
      
      - name: 3️⃣ Initializing twrp-12.1
        run: |
          yes | repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1

      - name: 4️⃣ Cloning twrp device tree.
        run: |
          sudo git clone https://github.com/SN-Abdullah-Al-Noman/a22_TWRP12.1_tree -b android-12.1 device/samsung/a22
          
      - name: 5️⃣ Sync Device Dependencies.
        run: |
          sudo bash convert.sh device/samsung/a22/twrp.dependencies && sudo repo sync -j$(nproc --all)

      - name: 6️⃣ Building twrp.
        run: |
          sudo source build/envsetup.sh && sudo export ALLOW_MISSING_DEPENDENCIES=true && sudo lunch twrp_a22-eng && sudo make clean && sudo make recoveryimage -j$(nproc --all)
